stages:
  data_ingestion:
    cmd: python src/pipelines/data_ingestion.py
    deps:
      - src/pipelines/data_ingestion.py
      - config/config.yaml
    outs:
      artifacts/data_ingestion/facial_expression_images
